/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      bg: 'var(--color-bg)',
      'bg-deep': 'var(--color-bg-deep)',
      surface: 'var(--color-surface)',
      'surface-raised': 'var(--color-surface-raised)',
      border: 'var(--color-border)',
      'border-bright': 'var(--color-border-bright)',
      'text-primary': 'var(--color-text-primary)',
      'text-secondary': 'var(--color-text-secondary)',
      'text-muted': 'var(--color-text-muted)',
      accent: 'var(--color-accent)',
      'accent-hover': 'var(--color-accent-hover)',
      'accent-soft': 'var(--color-accent-soft)',
      'accent-glow': 'var(--color-accent-glow)',
      cyan: 'var(--color-cyan)',
      'cyan-glow': 'var(--color-cyan-glow)',
      pink: 'var(--color-pink)',
      'pink-glow': 'var(--color-pink-glow)',
      error: 'var(--color-error)',
      success: 'var(--color-success)',
    },
    fontFamily: {
      sans: 'var(--font-family-sans)',
      mono: 'var(--font-family-mono)',
    },
    fontSize: {
      xs: 'var(--font-size-xs)',
      sm: 'var(--font-size-sm)',
      base: 'var(--font-size-base)',
      lg: 'var(--font-size-lg)',
      xl: 'var(--font-size-xl)',
      '2xl': 'var(--font-size-2xl)',
      '3xl': 'var(--font-size-3xl)',
      '4xl': 'var(--font-size-4xl)',
      '5xl': 'var(--font-size-5xl)',
      '6xl': 'var(--font-size-6xl)',
    },
    fontWeight: {
      normal: 'var(--font-weight-normal)',
      medium: 'var(--font-weight-medium)',
      semibold: 'var(--font-weight-semibold)',
      bold: 'var(--font-weight-bold)',
    },
    lineHeight: {
      tight: 'var(--line-height-tight)',
      base: 'var(--line-height-base)',
      relaxed: 'var(--line-height-relaxed)',
    },
    letterSpacing: {
      normal: '0',
      tracked: 'var(--letter-tracked)',
      wide: 'var(--letter-wide)',
    },
    spacing: {
      0: '0',
      1: 'var(--spacing-1)',
      2: 'var(--spacing-2)',
      3: 'var(--spacing-3)',
      4: 'var(--spacing-4)',
      5: 'var(--spacing-5)',
      6: 'var(--spacing-6)',
      7: 'var(--spacing-7)',
      8: 'var(--spacing-8)',
      9: 'var(--spacing-9)',
      10: 'var(--spacing-10)',
      11: 'var(--spacing-11)',
      12: 'var(--spacing-12)',
      13: 'var(--spacing-13)',
      14: 'var(--spacing-14)',
      15: 'var(--spacing-15)',
      16: 'var(--spacing-16)',
    },
    borderRadius: {
      none: '0',
      sm: 'var(--border-radius-sm)',
      md: 'var(--border-radius-md)',
      lg: 'var(--border-radius-lg)',
      xl: 'var(--border-radius-xl)',
      '2xl': 'var(--border-radius-2xl)',
      full: 'var(--border-radius-full)',
    },
    borderWidth: {
      0: '0',
      DEFAULT: 'var(--border-width)',
    },
    boxShadow: {
      none: 'none',
      sm: 'var(--shadow-sm)',
      md: 'var(--shadow-md)',
      lg: 'var(--shadow-lg)',
      glow: 'var(--shadow-glow)',
      'glow-soft': 'var(--shadow-glow-soft)',
    },
    transitionDuration: {
      fast: 'var(--transition-fast)',
      base: 'var(--transition-base)',
      slow: 'var(--transition-slow)',
    },
    transitionTimingFunction: {
      'out-quint': 'var(--ease-out-quint)',
      'in-out-quint': 'var(--ease-in-out-quint)',
    },
    extend: {
      animation: {
        'fade-in': 'fade-in var(--transition-slow) var(--ease-out-quint) both',
        'fade-in-up': 'fade-in-up var(--transition-slow) var(--ease-out-quint) both',
        'orb-a': 'orb-drift-a 18s ease-in-out infinite',
        'orb-b': 'orb-drift-b 22s ease-in-out infinite',
        'orb-c': 'orb-drift-c 26s ease-in-out infinite',
        'pulse-glow': 'pulse-glow 4s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
